# ba0fde3d-bee7-4307-b97b-17d0d20aff50
[customizations.installer.kickstart]
contents = ""

[customizations.installer.modules]
enable = [
    "org.fedoraproject.Anaconda.Modules.Localization",
    "org.fedoraproject.Anaconda.Modules.Timezone"
]